services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Mirko\Newsletter\:
    resource: '../Classes/*'
    exclude: ['../Classes/Domain/Model/*', '../Classes/Tca/*']

  Mirko\Newsletter\DataProvider\Backend\SendingPageDataProvider:
    arguments:
      $recipientListRepository: '@Mirko\Newsletter\Domain\Repository\RecipientListRepository'
      $newsletterRepository: '@Mirko\Newsletter\Domain\Repository\NewsletterRepository'
      $bounceAccountRepository: '@Mirko\Newsletter\Domain\Repository\BounceAccountRepository'

  Mirko\Newsletter\DataProvider\Backend\StatusPageDataProvider:
    arguments:
      $newsletterRepository: '@Mirko\Newsletter\Domain\Repository\NewsletterRepository'

  Mirko\Newsletter\DataProvider\Backend\StatisticPageDataProvider:
    arguments:
      $newsletterRepository: '@Mirko\Newsletter\Domain\Repository\NewsletterRepository'

  Mirko\Newsletter\Tools:
    arguments:
      $emailRepository: '@Mirko\Newsletter\Domain\Repository\EmailRepository'
      $newsletterRepository: '@Mirko\Newsletter\Domain\Repository\NewsletterRepository'